version: '3.7'

services:
  fanta_db:
    image: postgres:15.3-alpine
    volumes:
      - fanta_db_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=fanta_db_username
      - POSTGRES_PASSWORD=fanta_db_password
      - POSTGRES_DB=fanta_db
    container_name: fanta-db

volumes:
  fanta_db_data: